service: pp-data-dev

ssh:
  user: pp-admin

servers:
  web:
    hosts:
      - 192.168.1.137
    proxy: false
    options:
      publish:
        - '3306:3306'

builder:
  dockerfile: ./Dockerfile
  local: false
  arch: amd64
  remote: ssh://pp-admin@192.168.1.137
